Warning Fixes
boostorg/smart_ptr pull request #96
Opened 2022-07-16 19:27 UTC by mborland

Primarily replacing 0 with `BOOST_NULLPTR`, and a few other minor ones throughout the tests.

2022-07-16 19:28 UTC, mborland commented
@pdimov Can you please kick off the CI run for this?

2022-07-17 07:43 UTC, pdimov commented
This has too many unrelated changes in a single PR, sorry. Some of these are outright wrong; the self-assignments are there because _they test that self-assignment works_.

What problem (for you, or for users) is this PR trying to solve?

2022-07-19 16:14 UTC, mborland commented
> This has too many unrelated changes in a single PR, sorry. Some of these are outright wrong; the self-assignments are there because _they test that self-assignment works_.
> 
> What problem (for you, or for users) is this PR trying to solve?

I can cut out everything that is outside of the include directory. The changes to test files would be immaterial to users anyway; they helped me to root out the actual warnings.

2022-08-04 01:47 UTC, mborland commented
@pdimov I apologize for the delay in correcting this PR. Can you please kick off the CI run?

2022-08-07 16:26 UTC, mborland commented
@pdimov The CI run on this is clean. Let me know if you need any additional changes.

2022-08-07 17:12 UTC, glenfe requested changes

2022-08-07 17:12 UTC, glenfe commented on test/weak_ptr_test.cpp
> +        boost::shared_ptr<X> sp(static_cast<X*>(BOOST_NULLPTR));
static_cast<T*>(0) would never trigger the warning, even with -Wzero-as-null-pointer-constant

2022-08-07 17:12 UTC, glenfe commented on include/boost/smart_ptr/detail/shared_count.hpp
> +            }
Leave new brackets or whitespace changes out of it

2022-08-27 16:10 UTC, mborland commented
Ping @pdimov and @glenfe

2022-10-19 16:54 UTC, AtariDreams commented
Any update on this?

2024-12-14 14:43 UTC, closed without merging